name: Tag

on:
  push:
    branches: [ "master" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Release
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
